import json
from pathlib import Path

from app.src.Database import core as db
from app.src.Notifications.events import send_event

from .io_ops import extract_transcribe_audio, render_subtitled_video, write_transcript_files, zip_outputs
from .progress import emit_progress
from .whisper_engine import ENGINE


def _extract_segments(transcript_result):
    if isinstance(transcript_result, dict):
        segments = transcript_result.get("segments")
        if isinstance(segments, list):
            return segments
    return []


def _build_item_progress(index, total, inner):
    total_items = max(1, int(total or 1))
    clamped_inner = max(0.0, min(1.0, float(inner or 0.0)))
    base = (index - 1) / total_items
    return int(5 + (base + clamped_inner / total_items) * 90)


def _process_single_media(task_id, media_item, params, run_dir, index, total):
    media_path = Path(media_item.get("upload_path", ""))
    if not media_path.exists():
        raise RuntimeError(f"uploaded media missing: {media_item.get('filename')}")

    emit_progress(
        task_id,
        _build_item_progress(index, total, 0.05),
        f"转录文件 {index}/{total}: 准备中",
        file_index=index,
        file_count=total,
    )
    audio_path, info, created_temp_audio = extract_transcribe_audio(media_path, run_dir)
    try:
        emit_progress(
            task_id,
            _build_item_progress(index, total, 0.35),
            f"转录文件 {index}/{total}: 语音识别中",
            file_index=index,
            file_count=total,
        )
        result = ENGINE.transcribe(
            audio_path,
            model_name=params.get("whisper_model", "medium"),
            language=params.get("language", "auto"),
            temperature=params.get("temperature", 0.0),
            beam_size=params.get("beam_size", 5),
            best_of=params.get("best_of", 5),
        )
        segments = _extract_segments(result)
        if not segments:
            raise RuntimeError(f"no transcript segments extracted from {media_item.get('filename')}")

        emit_progress(
            task_id,
            _build_item_progress(index, total, 0.65),
            f"转录文件 {index}/{total}: 生成字幕",
            file_index=index,
            file_count=total,
        )
        output_dir = run_dir / "results"
        subtitle_path, outputs = write_transcript_files(
            output_dir,
            media_path.stem,
            segments,
            subtitle_format=params.get("subtitle_format", "srt"),
            prepend_timestamps=bool(params.get("prepend_timestamps", False)),
            max_line_chars=int(params.get("max_line_chars", 42) or 42),
        )

        mode = (params.get("transcribe_mode") or "subtitle_zip").strip().lower()
        if mode == "subtitled_video" and info.get("has_video"):
            video_codec = params.get("output_video_codec", "h264")
            audio_bitrate_k = params.get("output_audio_bitrate_k", 192)
            subtitled = output_dir / f"{media_path.stem}_subtitled.mp4"
            outputs.append(
                render_subtitled_video(
                    media_path,
                    subtitle_path,
                    subtitled,
                    video_codec,
                    audio_bitrate_k,
                )
            )
        return outputs
    finally:
        if created_temp_audio and audio_path.exists():
            try:
                audio_path.unlink()
            except Exception:
                pass


def process_transcription_task(task):
    task_id = task["task_id"]
    params = json.loads(task.get("task_params") or "{}")
    run_dir = Path("/workspace/storage/output") / f"run_{task_id}"
    run_dir.mkdir(parents=True, exist_ok=True)

    media_files = params.get("media_files") or []
    if not media_files:
        raise RuntimeError("No uploaded audio/video files for transcription.")

    emit_progress(task_id, 2, "转录任务初始化中...")
    all_outputs = []
    total = len(media_files)
    for idx, media_item in enumerate(media_files, start=1):
        all_outputs.extend(_process_single_media(task_id, media_item, params, run_dir, idx, total))

    if not all_outputs:
        raise RuntimeError("No output generated by transcription pipeline.")

    force_zip = len(media_files) > 1 or (params.get("transcribe_mode") or "subtitle_zip").lower() == "subtitle_zip"
    if force_zip:
        result_path = run_dir / "results" / f"transcribe_{task_id}.zip"
        zip_outputs(all_outputs, result_path)
    else:
        result_path = all_outputs[-1]

    db.update_task_result(task_id, result_path)
    db.update_task_status(task_id, "COMPLETED", 100, f"Completed: {Path(result_path).name}")
    send_event({"task_id": task_id, "progress": 100, "message": "转录任务已完成"})
