from .common import (
    bool_from_form,
    float_from_form,
    int_from_form,
    merge_unparsed_form_fields,
    parse_watermark_timeline,
)


def parse_conversion_task_params(form):
    parsed = {
        "task_category": "convert",
        "convert_mode": (form.get("convert_mode", "transcode") or "transcode").lower(),
        "output_format": (form.get("output_format", "mp4") or "mp4").lower(),
        "video_codec": (form.get("video_codec", "h264") or "h264").lower(),
        "frame_rate": int_from_form(form, "frame_rate", 0),
        "audio_source_mode": (form.get("audio_source_mode", "keep_original") or "keep_original").lower(),
        "audio_channels_mode": (form.get("audio_channels_mode", "keep") or "keep").lower(),
        "haas_enabled": bool_from_form(form, "haas_enabled", False),
        "haas_delay_ms": int_from_form(form, "haas_delay_ms", 0),
        "haas_lead": (form.get("haas_lead", "left") or "left").lower(),
        "aspect_ratio": (form.get("aspect_ratio", "") or "").strip(),
        "second_pass_reencode": bool_from_form(form, "second_pass_reencode", False),
        "deinterlace": bool_from_form(form, "deinterlace", False),
        "flip_horizontal": bool_from_form(form, "flip_horizontal", False),
        "flip_vertical": bool_from_form(form, "flip_vertical", False),
        "video_fade_in_sec": float_from_form(form, "video_fade_in_sec", 0.0),
        "video_fade_out_sec": float_from_form(form, "video_fade_out_sec", 0.0),
        "crf": int_from_form(form, "crf", 18),
        "video_bitrate_k": int_from_form(form, "video_bitrate_k", 0),
        "target_size_mb": float_from_form(form, "target_size_mb", 0.0),
        "target_width": int_from_form(form, "target_width", 0),
        "target_height": int_from_form(form, "target_height", 0),
        "audio_sample_rate": int_from_form(form, "audio_sample_rate", 0),
        "audio_bitrate_k": int_from_form(form, "audio_bitrate_k", 192),
        "mute_audio": bool_from_form(form, "mute_audio", False),
        "audio_fade_in_sec": float_from_form(form, "audio_fade_in_sec", 0.0),
        "audio_fade_out_sec": float_from_form(form, "audio_fade_out_sec", 0.0),
        "audio_echo": bool_from_form(form, "audio_echo", False),
        "audio_echo_delay_ms": int_from_form(form, "audio_echo_delay_ms", 200),
        "audio_echo_decay": float_from_form(form, "audio_echo_decay", 0.4),
        "audio_denoise": bool_from_form(form, "audio_denoise", False),
        "audio_reverse": bool_from_form(form, "audio_reverse", False),
        "audio_volume": float_from_form(form, "audio_volume", 1.0),
        "meta_title": form.get("meta_title", ""),
        "meta_author": form.get("meta_author", ""),
        "meta_comment": form.get("meta_comment", ""),
        "watermark_enable_text": bool_from_form(form, "watermark_enable_text", False),
        "watermark_enable_image": bool_from_form(form, "watermark_enable_image", False),
        "watermark_default_text": form.get("watermark_default_text", ""),
        "watermark_alpha": float_from_form(form, "watermark_alpha", 0.45),
        "watermark_timeline": parse_watermark_timeline(form.get("watermark_timeline")),
        "watermark_yaml_config": form.get("watermark_yaml_config", ""),
        "watermark_lua_script": form.get("watermark_lua_script", ""),
        "frame_export_fps": int_from_form(form, "frame_export_fps", 0),
        "frame_export_fps_mode": (form.get("frame_export_fps_mode", "manual") or "manual").lower(),
        "frame_export_format": (form.get("frame_export_format", "jpg") or "jpg").lower(),
    }
    return merge_unparsed_form_fields(form, parsed)
