export const CATEGORY_FIELD_MAP = Object.freeze({
  enhance: Object.freeze({
    inputType: "input_type",
    modelName: "model_name",
    upscale: "upscale",
    tile: "tile",
    denoise: "denoise_strength",
    keepAudio: "keep_audio",
    audioEnhance: "audio_enhance",
    preDenoiseMode: "pre_denoise_mode",
    haasEnabled: "haas_enabled",
    haasDelayMs: "haas_delay_ms",
    haasLead: "haas_lead",
    crf: "crf",
    outputCodec: "output_codec",
    deinterlace: "deinterlace",
  }),
  convert: Object.freeze({
    convertMode: "convert_mode",
    outputFormat: "output_format",
    videoCodec: "video_codec",
    frameRate: "frame_rate",
    audioSourceMode: "audio_source_mode",
    audioChannelsMode: "audio_channels_mode",
    haasEnabled: "haas_enabled",
    haasDelayMs: "haas_delay_ms",
    haasLead: "haas_lead",
    aspectRatio: "aspect_ratio",
    secondPassReencode: "second_pass_reencode",
    deinterlace: "deinterlace",
    flipHorizontal: "flip_horizontal",
    flipVertical: "flip_vertical",
    videoFadeInSec: "video_fade_in_sec",
    videoFadeOutSec: "video_fade_out_sec",
    crf: "crf",
    videoBitrateK: "video_bitrate_k",
    targetSizeMb: "target_size_mb",
    targetWidth: "target_width",
    targetHeight: "target_height",
    audioSampleRate: "audio_sample_rate",
    audioBitrateK: "audio_bitrate_k",
    muteAudio: "mute_audio",
    audioFadeInSec: "audio_fade_in_sec",
    audioFadeOutSec: "audio_fade_out_sec",
    audioEcho: "audio_echo",
    audioEchoDelayMs: "audio_echo_delay_ms",
    audioEchoDecay: "audio_echo_decay",
    audioDenoise: "audio_denoise",
    audioReverse: "audio_reverse",
    audioVolume: "audio_volume",
    metaTitle: "meta_title",
    metaAuthor: "meta_author",
    metaComment: "meta_comment",
    watermarkEnableText: "watermark_enable_text",
    watermarkEnableImage: "watermark_enable_image",
    watermarkDefaultText: "watermark_default_text",
    watermarkAlpha: "watermark_alpha",
    frameExportFps: "frame_export_fps",
    frameExportFpsMode: "frame_export_fps_mode",
    frameExportFormat: "frame_export_format",
  }),
  transcribe: Object.freeze({
    transcribeMode: "transcribe_mode",
    subtitleFormat: "subtitle_format",
    whisperModel: "whisper_model",
    language: "language",
    translateTo: "translate_to",
    translatorProvider: "translator_provider",
    translatorBaseUrl: "translator_base_url",
    translatorModel: "translator_model",
    translatorApiKey: "translator_api_key",
    translatorPrompt: "translator_prompt",
    translatorTimeoutSec: "translator_timeout_sec",
    generateBilingual: "generate_bilingual",
    exportJson: "export_json",
    prependTimestamps: "prepend_timestamps",
    maxLineChars: "max_line_chars",
    temperature: "temperature",
    beamSize: "beam_size",
    bestOf: "best_of",
    outputVideoCodec: "output_video_codec",
    outputAudioBitrateK: "output_audio_bitrate_k",
  }),
});

export const CATEGORY_FIELD_MAP_REVERSED = Object.freeze(
  Object.fromEntries(
    Object.entries(CATEGORY_FIELD_MAP).map(([category, mappings]) => {
      const reversed = Object.fromEntries(Object.entries(mappings).map(([formKey, apiKey]) => [apiKey, formKey]));
      return [category, Object.freeze(reversed)];
    })
  )
);
