services:
  better_video:
    build:
      context: ../..
      dockerfile: deploy/docker/for-app/Dockerfile
    container_name: better_video
    network_mode: host
    volumes:
      - ../../:/workspace
      - ../../pre-run/.env:/workspace/config/.env
    environment:
      PYTHONPATH: "/workspace/app:${PYTHONPATH}"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,video
    runtime: nvidia
    ipc: host
    command: python3 app/main.py
